# Generated by Django 3.1.4 on 2021-03-20 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
