# Generated by Django 3.2.6 on 2021-08-20 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todoitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.utcnow),
        ),
    ]
