# Generated by Django 3.1.4 on 2021-04-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasteX', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastexitem',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
