# Generated by Django 3.1.4 on 2021-04-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasteX', '0002_auto_20210405_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastexitem',
            name='language',
            field=models.TextField(default='plaintext'),
            preserve_default=False,
        ),
    ]
