# Generated by Django 3.1.4 on 2021-04-06 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formatter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormatterItem',
        ),
    ]
