# Generated by Django 3.1.4 on 2021-06-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkyItem',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
