# Generated by Django 3.2.6 on 2022-05-13 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
